### ISSUE TITLE
e-mail broken : basic authentication not allowed with 2FA enabled

### ISSUE THREAD

**Issue by bourgeoa** [solid/solidcommunity.net#23]
@justinwb @jaxoncreed @michielbdejong 

Testing v5.5.3 but not related to v5.5.3

solidcommunity.net is using a sendgrid account to send mails.
Apparently the policy as from 4 quart 2020 do not allow any more basic-authentification
```
Invalid login: 535 Authentication failed: Basic authentication is not allowed with 2FA enabled.
To fix, see https://sendgrid.com/docs/for-developers/sending-email/authentication/#basic-authentication
```
![image](https://user-images.githubusercontent.com/2218470/97721654-fff61c80-1ac9-11eb-9226-b78941c4baf4.png)

**Comment by bourgeoa** [comment]
Could this be part of the solution : 
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-18-04

**Comment by justinwb** [comment]
There was an issue with the mail relay account. Was able to resolve that, and just received mail from a test of forgot password reset. If you can confirm it's also working for you I think you can go ahead and resolve this.

_Note that you'll need to update the mail config for the test server as well_

**Comment by bourgeoa** [comment]
Thanks @justinwb 
resolved its working for current and test server

**Comment by bourgeoa** [comment]
@justinwb Sorry in fact I mistakenly resend twice the reset passwd on solidcommunity.net

It is not resolved for solidcommunity.net:8443
I made a pm2 restart and cleared the browser cache

**Comment by justinwb** [comment]
@bourgeoa 

> _Note that you'll need to update the mail config for the test server as well_

;)  I should've gone ahead and done that last night at the same time. Should be resolved for both now.

**Comment by bourgeoa** [comment]
@justinwb Thanks. Sorry I need to learn to read slowly
