### ISSUE TITLE
One particular  resource always times out on GET

### ISSUE THREAD

**Issue by timbl** [solid/solidcommunity.net#24]
Here is a problem which has not gone away — I can never raed https://solidos.solidcommunity.net/Team/SolidOs%20team%20chat/2020/11/06/chat.ttl
as it times out
with browser or with curl

**Comment by timbl** [comment]
```Error: Fetcher: Request to https://solidos.solidcommunity.net/Team/SolidOs%20team%20chat/2020/11/06/chat.ttl timed out```

**Comment by timbl** [comment]
hmmm maybe others time out   like https://solidos.solid.community/Team/docs/solidos.html  or maybe the server crashes and goes down for a while

**Comment by bourgeoa** [comment]
Should be closed. It was an ACL problem due to migration.
