### ISSUE TITLE
Crash i've crashed and deleted https://cdr.solidcommunity.net/

### ISSUE THREAD

**Issue by scenaristeur** [solid/solidcommunity.net#27]
I've just crashed https://cdr.solidcommunity.net/ When trying to add index.html with css & js and can not have anything on it now.
can anyone restore it ?

Thxs

**Comment by bourgeoa** [comment]
@scenaristeur 
I went to solidcommunity.net server and your pod do not exist anymore. The key do exist but not the pod anymore.

I think you should comment a bit more what you did because this should not happen. You seem to have accessed the root of your pod and deleted everything.

**Comment by scenaristeur** [comment]
Hi @bourgeoa i've used @jeff-zucker solid-fild-client move.

Sorry for the inconvenience.
i had a dist folder at https://cdr.solidcommunity.net/public/vuejs/fullapp/dist/ with an .index.html, /js & /css. 
I thought i could change my landing page adding this index.html at the root so i started moving each folder and index.html using [poPock Editor](https://scenaristeur.github.io/solid-vue-panes/editor) (blue button near the vacccum)

![image](https://user-images.githubusercontent.com/4020744/99983772-90afd780-2dac-11eb-952f-3bc68cc1adc7.png)

- my code has nothing particular using fc.move https://github.com/scenaristeur/solid-vue-panes/blob/ab5ed477fe4c136a715fb811b5044b589fc1f744/src/components/explorer/Explorer.vue#L240

- solid-file-client move behavior : https://github.com/jeff-zucker/solid-file-client/blob/master/docs/JSdoc/api.md#SolidAPI+move
Hopefully, i didn't close the window and have the console.log : 

![image](https://user-images.githubusercontent.com/4020744/99980730-dc608200-2da8-11eb-9eae-001076d2a698.png)


The message for css and js folder should be the same but are not : 
```
Move folder https://cdr.solidcommunity.net/public/vuejs/fullapp/dist/css/ to https://cdr.solidcommunity.net/
Move text/html https://cdr.solidcommunity.net/public/vuejs/fullapp/dist/index.html to https://cdr.solidcommunity.net/index.html
Move folder https://cdr.solidcommunity.net/public/vuejs/fullapp/dist/js/ to https://cdr.solidcommunity.net/js/
```

As you can see i've forgotten to put the css folder at the end of the new_location, it should be 'https://cdr.solidcommunity.net/css/' instead of 'https://cdr.solidcommunity.net/' i think this is the cause

**Comment by bourgeoa** [comment]
@jeff-zucker do you agree
@scenaristeur 
Yes I suppose it is the cause, by default solid-file-client deletes the destination folder when using option replace
Then I suppose it is a bug : 
- in NSS which should not allow deletion of the root folder and some other that I call system folders like (profile, inbox, settings, .well-known) there is an open issue I think
- and also in solid-file-client that should refuse to delete them either directly or using option replace.
@jeff-zucker do you agree ?

Can you open an issue in both NSS and solid-file-client linking to this issue.

I suppose you cannot re-create the pod with the same name ? If so I can delete the index to clean the server even if you do not want to re-use the podName.

**Comment by jeff-zucker** [comment]
Yes, I definitely agree.  It is even in the spec that deletion of root folder must fail.

**Comment by scenaristeur** [comment]
@bourgeoa is there no way to retrieve my data ?

**Comment by bourgeoa** [comment]
@scenaristeur We are looking to see if we can recover your pod from a snapshot a few days old (?). I think it will be a first for solidcommunity.net. Toujours apprendre !!!

>maigre butin pour un double-bug ;-)

La destruction malencontreuse de dossier arrivera toujours, c'est un problème des 'delete' récursif surtout dans les fonctions combinés tel que 'move'. C'est pourquoi je privilégie la séparation 'copie vers un répertoire vide, puis suppression de l'ancien répertoire. Learned the hard way.

**Comment by scenaristeur** [comment]
Merci en tout cas ;-)
