### ISSUE TITLE
Delete pod

### ISSUE THREAD

**Issue by naturzukunft** [solid/solidcommunity.net#28]
1. i created a pod (https://xyz12.solidcommunity.net/profile/card#me) for testing something.
2. on the preference page i clicked on "Delete account -> Delete your account at https://xyz12.solidcommunity.net/"
3. i got an email, see screenshot
![grafik](https://user-images.githubusercontent.com/47322487/100005927-024a4e80-2dca-11eb-8618-7eb2dce42bd0.png)
4. the profile is still there and i can login to it.

I used this email: xyz@trash-mail.com
See: https://www.trash-mail.com

user is "xyz12"
pwd: "elektroroller12!"

Feel free to delete the account!

**Comment by bourgeoa** [comment]
@naturzukunft
You should have received an e-mail with a confirm link to delete your pod.
 
I just tried to reproduce this on my test pod and on my solidcommunity.net pod.
For both I received an e-mail with a link to confirm the delete.
Did you use the link in the `preferences page` ? Can you retry ? Could it be that the e-mail provider refuse such e-mail with a confirm link ?
I'm using a regular gmail account

**Comment by naturzukunft** [comment]
Hi, which email is used to send the confirmation link? thats absolutely unclear, isn't it? in the pod i had three dummy mails. no i deleted two of them and add the correct one. but still there is no emal.
- Did you use the link in the preferences page ? ->yes
-  Can you retry  -> yes, u also can retry it with the data above!
- Could it be that the e-mail provider refuse such e-mail with a confirm link ? -> i dont think so. goto https://www.trash-mail.com and put xyz@trash-mail.com in there. then you can see all received emails since you call the site. i cannot belive, that they do any filtering.

**Comment by bourgeoa** [comment]
Thanks for trying.
 Where do you change the email ?
I must check but I think that the email used is the pod creator one that is stored outside the pod in the .db keys.

**Comment by naturzukunft** [comment]
Hi,
"Where do you change the email ?" -> in the VCARD.
"in the .db" -> that is what i've expected. 

I again checked the mails avove and saw MY fault. i started with "xyz" but there was already a pod. so i used "xyz12" but the email i used was still "xyz@trash-mail.com". 
And i always checked "xyz12@trash-mail.com" ;-(

Sorry for the confusion. Now i was able to delete the pod!

Thanks
