### ISSUE TITLE
Registration email sends tracking pixel

### ISSUE THREAD

**Issue by jeff-zucker** [solid/solidcommunity.net#30]
See https://github.com/solid/node-solid-server/issues/1532 (probably not an NSS issue, but impacts inrupt.net as well.

**Comment by bourgeoa** [comment]
@justinwb is this you can check. You stated that solidcommunity.net was using an email on sendgrid.

I fund some information on the spy-tracking when using sendgrid mail https://community.auth0.com/t/howto-disable-sendgrids-click-tracking-feature-in-an-auth0-email-template/22958

**Comment by nicolasmondada** [comment]
Thanks @jeff-zucker (and everyone else on the original thread) for resporting this.

This was triggered by a default setting in Sendgrid, which is used by Inrupt for email delivery. This has now been corrected by disabling the option in Sendgrid. Apologies for any inconveniencies!
