### ISSUE TITLE
not getting password recovery email

### ISSUE THREAD

**Issue by sideshowtom** [solid/solidcommunity.net#31]
pretty sure I provided the email address when I created the pod

**Comment by bourgeoa** [comment]
Can you give me your pod's name. I will check the situation.

**Comment by bourgeoa** [comment]
I found the following pod https://sideshowtom.solidcommunity.net
the user key and the mail key are present
the email is sideshowtom@yahoo.com

When creating your pod you should have received a **greeting mail** : did you get it ?
When trying to reset your password, did you file your username `sideshowcom` not the podname and did you see a popup with something like email send ?

I just did it and it works perfectly for https://bourgeoa.solidcommunity.net

Did you check your mailbox for spam ?

**Comment by sideshowtom** [comment]
ooooh sorry.  it was in the spam.  apologies @bourgeoa !

**Comment by bourgeoa** [comment]
I close the issue
