### ISSUE TITLE
The `www` pod is taken and is confusing

### ISSUE THREAD

**Issue by Vinnl** [solid/solidcommunity.net#34]
See https://gitter.im/solid/chat?at=60069a62753011449b01803b

Someone has claimed the Pod `www.`, which is confusing for people (understandably) visiting `www.solidcommunity.net`.

**Comment by csarven** [comment]
Wasn't there a list of reserved account names somewhere?

**Comment by bourgeoa** [comment]
Yes there is such a list that actually only contains the big userNameBlacklist
There no specific reserved name.

I think that `www` should be added as default in all NSS instances for a few reasons : 
- browser tend to not display `https://www.xxxx` but only `xxxx`
- https://www.solidcommunity.net seems an official representation of solidcommunity.net

A few more words could be added to solidcommunity.net , like solid, solidos, solidweb ..., When the solid group wants to use one of them, it can be deleted from the list at that time.

I added `www` it in solidcommunity.net and was unable to create the www user

The pod https://www.solidcommunity.net pod is absolutely void. If there is consensus : 
1. I could delete it as a not correctly migrated pod with information to the owner
2. or we can ask the actual user to delete it if there is an email link

**Comment by Vinnl** [comment]
Also reported by @mariadimou at https://github.com/solid/solid-ui/issues/393:

> Olivier was very smart to name his pod 'www' but now we all suffer from
> [www.solidcommunity.net](http://www.solidcommunity.net) showing the appended confusing page
> instead of being an alias of solidcommunity.net.
> 
> Many CERN users were totally put off by this situation.
> I discussed this with @jeff-zucker and @timbl in the https://gitter.im/solid/solidos channel on April 13th 2021.
> They agreed it should be fixed.
> 
> See screenshot.
> ![Screenshot from 2021-04-20 19-15-52](https://user-images.githubusercontent.com/26465927/115438283-8126a480-a20d-11eb-8b77-99d3ff003f9a.png)
> ![Screenshot from 2021-04-20 19-20-08](https://user-images.githubusercontent.com/26465927/115438299-85eb5880-a20d-11eb-8d61-ca131c5461ae.png)

**Comment by bourgeoa** [comment]
@Vinnl
wwwsolidcommunity.net pod has been removed after checking it was really void.
It was created before the blacklist was implemented. Cannot be recreated.
