### ISSUE TITLE
"can't parse container" https://spoggy-test9.solidcommunity.net/workspaces/

### ISSUE THREAD

**Issue by scenaristeur** [solid/solidcommunity.net#36]
Hi all, 
playing with a pod and trying to createFile with @jeff-zucker https://github.com/jeff-zucker/solid-file-client i've lost access to 
https://spoggy-test9.solidcommunity.net/workspaces/ folder .
 I got a 500 Internal server error with a message 'Can't parse container'

I made a 

```
await fc.createFile(url, JSON.stringify(this.post.data), 'application/json' )
```
but the url was not the url of a file but the url of the container so I think the json data has overridden /miscreated the /workspaces folder instead of creating a file within

I've tryed to delete /workspaces myself but i can't, can some admin delete https://spoggy-test9.solidcommunity.net/workspaces/ folder ? 
Thxs

**Comment by bourgeoa** [comment]
@scenaristeur You may have been able to delete https://spoggy-test9.solidcommunity.net/workspaces/.meta

I just renamed .meta to .meta.txt the content is json not a valid RDF (turtle)
So Your problem do not seem to be 
> await fc.createFile(url, JSON.stringify(this.post.data), 'application/json' )

but the following issue https://github.com/solid/node-solid-server/issues/1548 still open in NSS 5.6.1

**Comment by bourgeoa** [comment]
There should be an issue also in solid-file-client that did not check that the url end's with /
Well strange that the file created was .meta. This was the way POST ended to create a folder. It is finished in NSS 5.6.1 where the folder is directly created not going to .meta file.

Can you report the issue in solid-file-client.

**Comment by scenaristeur** [comment]
> Well strange that the file created was .meta. This was the way POST ended to create a folde

perhaps I've tried with postFile too

**Comment by jeff-zucker** [comment]
I have added the check to disallow  creation of '/foo/ ' if '/foo' exists and vice versa in next release of solid-rest. That should solve it in solid-file-client.

**Comment by bourgeoa** [comment]
Nice @jeff-zucker but solid-file-client is not using solid-rest.
- in NSS .meta is parsed to build the container triples. This implies the body is valid turtle. The check is not done actually
- in SFC createFile() should fail if the URL is a folder. But the point is may be a bit different. I shall check

**Comment by jeff-zucker** [comment]
>  but solid-file-client is not using solid-rest.
> 
Yes, it can use solid-rest for file:// requests.  For https:// requests, the server should return an error which takes no more resources than it would for the client to check if an error will occur, so I do not see a reason to have solid-file-client check for it in advance.  Perhaps I'm missing something.

**Comment by scenaristeur** [comment]
thxs , for me its ok, can we close this issue ?
