### ISSUE TITLE
SSL cert for old website just expired

### ISSUE THREAD

**Issue by uart-byte** [solid/solidcommunity.net#37]
The LetsEncrypt SSL certificate for the old website https://solid.mit.edu/ has just expired as of Feb 10th.  I know that website isn't considered active anymore, but I think that it's best to fix the cert if possible, because right now when people like me who are security-conscious try to learn about Solid, their browser tells them not to trust it.
![image](https://user-images.githubusercontent.com/70259728/107857652-879b3900-6de4-11eb-8847-2880fe9e83ad.png)

**Comment by justinwb** [comment]
Thanks for the heads up @uart-byte. This has been resolved ✅
