### ISSUE TITLE
https://solidcommunity.net/ is down

### ISSUE THREAD

**Issue by scenaristeur** [solid/solidcommunity.net#47]
Hi does anyone know why https://solidcommunity.net/ is down ? 

![image](https://user-images.githubusercontent.com/4020744/126276509-8f4decf5-d322-48f3-bf12-a0afb0ec5798.png)

**Comment by michielbdejong** [comment]
I just rebooted the server, but pm2 didn't restart any process at startup, it seems.
Where do we have the documentation for the server setup?

**Comment by michielbdejong** [comment]
I found `/home/solid/test-solid` which must be the test server.
Maybe the main production instance lives in `/usr/local/lib/node_modules/solid-server` ?

**Comment by scenaristeur** [comment]
hi @michielbdejong here is the old repo https://gitlab.com/solid.community/support/-/issues?scope=all&state=all with what was done and when. Could it help ?

**Comment by michielbdejong** [comment]
Hm, this seems to come close but not working yet:
```sh
 cd /root/solid-config/
pm2 start /usr/local/bin/solid start
```

**Comment by michielbdejong** [comment]
I started it in a screen now. So the server is up. But we should configure it with pm2 again. Will leave that to @bourgeoa!

**Comment by michielbdejong** [comment]
OK it looks ok again now:
```sh
root@solidcommunity:~# pm2 list
┌─────┬───────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name          │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 3   │ solid         │ default     │ N/A     │ fork    │ 7406     │ 2m     │ 177  │ online    │ 0%       │ 122.1mb  │ root     │ disabled │
│ 0   │ test-solid    │ default     │ 5.6.8   │ fork    │ 4070     │ 2h     │ 0    │ online    │ 0%       │ 86.6mb   │ root     │ disabled │
└─────┴───────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
root@solidcommunity:~# pm2 save
[PM2] Saving current process list...
[PM2] Successfully saved in /root/.pm2/dump.pm2
root@solidcommunity:~#
```

The server came back up ok, out and of itself, after a reboot, so I think it's back in action.
