### ISSUE TITLE
Add link to github solidcommunity.net, gitter channel, forum on solidcommunity page?

### ISSUE THREAD

**Issue by phochste** [solid/solidcommunity.net#67]
Would it be a good idea to add a link to github projec/gitter/forum on the https://solidcommunity.net page?

I got myself locked out of my own pod and didn't find any information on the solidcommunity server pages itself where I could find a contact for help. 

At the end I found my way, because I am long enough in the community to find the right channels (but I didn't know there was a dedicated gitter channel also)  

E.g. a "Do you have any question? Please find us on [Github](https://github.com/solid/solidcommunity.net) , [Gitter](https://gitter.im/solid/solidcommunity.net) and [Solid Community Forum](https://forum.solidproject.org)" would be enough

See also: https://forum.solidproject.org/t/locked-out-a-pod-and-what-next/5813/4

**Comment by bourgeoa** [comment]
Done. Thanks for the suggestion
