### ISSUE TITLE
Broken account on solidcommunity.net, who to contact?

### ISSUE THREAD

**Issue by tehabe** [solid/solidcommunity.net#74]
I have an unused account on solidcommunity.net it gives me mostly 403 errors and other error messages. I created it years ago with no purpose and I have not even a way to use it or delete it. It seems that there is no email associated with the account and I can't change anything about it.

URL is https://tehabe.solidcommunity.net/

Thanks in advance.

**Comment by bourgeoa** [comment]
Your account/pod has been fully deleted
Alain
