### ISSUE TITLE
Missing redirect server from http: to https: 

### ISSUE THREAD

**Issue by timbl** [solid/solidcommunity.net#8]
http://*.solidcommunity.net/ could do with  a redirect to  https: 

```
$ curl http://solidos.solidcommunity.net/
curl: (7) Failed to connect to solidos.solidcommunity.net port 80: Connection refused

```

**Comment by bourgeoa** [comment]
@timbl I used to be a server maintainer on `solid.community server` and implemented the fonctionality.

If the server IP as not changed, I do not have anymore an access to solidcommunity.net server and would be happy to gain the same ability respecting detail reporting, data's confidentiality and data security.

I have  also made most of gitlab.com/solid.community and am a maintainer of NSS

**Comment by bourgeoa** [comment]
Redirect done with nginx : tested on `http://solidcommunity.net` and `http://solidcommunity:8443` 

the setup was the following with nginx :

This is the block rule :
```
# redirect all http to https
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}
```
and the process followed :
```
apt-get install nginx => OK (installed with port 80 rule)
systemctl status nginx => Nginx active (tested also with http://solid.community => Welcome to Nginx
cd /etc/nginx/sites-available
vi http_to_https => create file with block rule for http to https
cd /etc/nginx/sites-enabled
ln -s /etc/nginx/sites-available/http_to_https http_to_https
rm default
nginx -t => test configuration is OK
systemctl reload nginx
```

**Comment by bourgeoa** [comment]
Done should be closed

**Comment by justinwb** [comment]
Working for me - thanks! @bourgeoa ✅
